1.1: Switch to GPLv3 and improve the code
Signed-off-by: Ari Archer <ari.web.xyz@gmail.com>

diff --git a/bdwmb b/bdwmb
--- a/bdwmb
+++ b/bdwmb
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+[ "$DEBUG" ] && set -x
+set -e
+
 die() {
     echo "FATAL ERROR: $1" >&2
     xsetroot -name "$1"
@@ -7,7 +10,6 @@ die() {
     exit 1
 }
 
-[ ! -d "$HOME" ] && die "'$HOME' is not a valid HOME directory"
 . "$HOME/.config/bdwmb/config.sh" || die 'the configuration file was not found'
 
 vecho() {
@@ -24,7 +26,7 @@ print_help() {
 main() {
     case "$1" in
     -q | --q | -quiet | --quiet)
-        vecho() { printf ''; }
+        vecho() { :; }
         ;;
     -h | --h | -help | --help)
         print_help
@@ -40,23 +42,22 @@ main() {
         ;;
     esac
 
-    local module
-    local bar_text
+    while true; do
+        bar_text=
 
-    for module in "${MODULES[@]}"; do
-        . "$HOME/.config/bdwmb/modules/$module" 2>/dev/null ||
-            . "/usr/share/bdwmb/modules/$module" 2>/dev/null ||
-            die "Failed to load module $module"
+        for module in "${MODULES[@]}"; do
+            . "$HOME/.config/bdwmb/modules/$module" 2>/dev/null ||
+                . "/usr/share/bdwmb/modules/$module" 2>/dev/null ||
+                die "Failed to load module $module"
 
-        vecho "Loading: $module (b$module)"
-        bar_text+="$("b$module")"
+            vecho "Loading: $module (b$module)"
+            bar_text+="$("b$module")"
+        done
+        vecho
+
+        xsetroot -name "$bar_text"
+        [ "$DELAY" ] && sleep -- "$DELAY"
     done
-    vecho
-
-    xsetroot -name "$bar_text"
 }
 
-while true; do
-    main "$@"
-    [ "$DELAY" ] && sleep -- "$DELAY"
-done
+main "$@"
